# Generated by Django 6.0.2 on 2026-02-21 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, help_text='Upload a PDF or Word document.', null=True, upload_to='submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, help_text='Submit your work here. You can include links to external files if needed.', null=True),
        ),
    ]
