# Generated by Django 6.0.2 on 2026-02-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_file_alter_submission_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='teacher_grade',
            field=models.IntegerField(blank=True, help_text='Official grade from teacher', null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_remarks',
            field=models.TextField(blank=True, help_text='Remarks from teacher', null=True),
        ),
    ]
