# Generated by Django 4.2.28 on 2026-02-22 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_teacher_grade_submission_teacher_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peerreview',
            name='feedback',
            field=models.TextField(help_text='Provide constructive feedback for your peer.'),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='grade',
            field=models.IntegerField(help_text='Grade from 1 to 100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='teacher_grade',
            field=models.IntegerField(blank=True, help_text='Official grade from teacher (1-100)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
