# Generated by Django 4.2.28 on 2026-02-22 12:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('total_points', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubric', to='core.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='core.assignmentrubric')),
            ],
            options={
                'verbose_name_plural': 'Rubric Criteria',
            },
        ),
        migrations.CreateModel(
            name='RevisionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField(default=1)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/revisions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('improvement', models.IntegerField(blank=True, help_text='Grade improvement from previous', null=True)),
                ('original_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.submission')),
            ],
            options={
                'ordering': ['original_submission', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewQualityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_length', models.IntegerField()),
                ('constructiveness_score', models.IntegerField(help_text='1-5 scale for constructiveness', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('specificity_score', models.IntegerField(help_text='1-5 scale for specificity', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_quality', models.IntegerField(help_text='Overall quality percentage', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_metric', to='core.peerreview')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('improvement', 'Shows Improvement'), ('declining', 'Declining Performance'), ('excellent', 'Excellent Performance'), ('struggling', 'Struggling'), ('consistent', 'Consistent Performance')], max_length=20)),
                ('message', models.TextField()),
                ('recommendation', models.TextField()),
                ('trend_percentage', models.FloatField(help_text='Percentage change in performance')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_trends', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_trends', to='core.submission')),
            ],
            options={
                'ordering': ['student', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_peer_grade', models.FloatField()),
                ('total_reviews', models.IntegerField()),
                ('positive_feedback_count', models.IntegerField(default=0)),
                ('improvement_feedback_count', models.IntegerField(default=0)),
                ('common_themes', models.TextField(blank=True, help_text='Common themes in feedback')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_summary', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ClassAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_grade', models.FloatField()),
                ('highest_grade', models.IntegerField()),
                ('lowest_grade', models.IntegerField()),
                ('submission_rate', models.FloatField(help_text='Percentage of students who submitted')),
                ('on_time_submission_count', models.IntegerField()),
                ('late_submission_count', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_analytics', to='core.assignment')),
                ('at_risk_students', models.ManyToManyField(blank=True, related_name='at_risk_in_assignments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_analytics_records', to=settings.AUTH_USER_MODEL)),
                ('top_performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_performer_in', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeadlineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('24h', '24 Hours Before'), ('7d', '7 Days Before'), ('1d', '1 Day Before')], default='1d', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadline_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student', 'reminder_type')},
            },
        ),
    ]
